version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: IDP/Dockerfile
    depends_on:
        - sqldata
  sqldata:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"